### ISSUE TITLE
[Improvement] Use db credentials from secret for appwrite pods

### ISSUE THREAD

**Issue by Lai0n** [fpoussin/appwrite-helm#2]
**What is the problem?**
Currently secret that gets injected into appwrite pods with db credentials will take data from chart values even when you set `mariadb.auth.existingSecret`, which basically defies the reason to use secret at all.

**Proposal**
Add mapping to appwrite pods for db credentials to be re-used from secret referenced by `mariadb.auth.existingSecret` when it's set.

**Comment by fpoussin** [comment]
This is specific to the MariaDB helm chart.
Since var names are different between Appwrite and MariaDB, this can't be used in the current state.

**Comment by fpoussin** [comment]
This should work now, could you confirm before I do a release?
